name: Bug Report
description: File a bug report
title: "[bug]: "
labels: ["bug"]
assignees:
  - ungiglio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? (you can also attach images)
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our theme are you running?
      options:
        - 1.1.1 (latest)
        - 1.1.1 backgroundless
        - 1.1.0
        - previous version
      default: 0
    validations:
      required: true
  - type: textarea
    id: theme-version
    attributes:
      label: Theme version
      description: Theme version can be found at very bottom of settings page above discord version, pls copy below the \# number.
      placeholder: Ex. (#20250308)
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: What client are you seeing the problem on?
      multiple: true
      options:
        - Desktop app
        - Browser
        - Mobile
    validations:
      required: true
  - type: dropdown
    id: clientmod
    attributes:
      label: What client mod are you seeing the problem on?
      multiple: true
      options:
        - Vencord
        - BetterDiscord
        - Not listed (specify in textarea)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        **Priority Labels**
        Please select the appropriate priority label for this bug:
        - High: Critical issues that severely impact core functionality or affect a large number of users. Requires immediate attention.
        - Medium: Important issues that affect some users or non-critical features. Should be addressed in the near future.
        - Low: Minor issues or cosmetic problems that don't significantly impact functionality. Can be addressed in future updates.
  - type: dropdown
    id: priority
    attributes:
      label: Bug Priority
      description: Select the priority level for this bug based on its impact and urgency.
      options:
        - High
        - Medium
        - Low
      default: 2
    validations:
      required: true
  - type: checkboxes
    id: validation
    attributes:
      label: Final Checklist
      description: Please review and confirm the following before submitting
      options:
        - label: I have selected the appropriate priority level for this bug.
          required: true
        - label: I have double-checked all the information in this report for accuracy.
          required: true
